version: '3'

services:
  backend:
    build: ./backend
    ports:
      - '127.0.0.1:4000:4000'
    links:
      - mongo:mongo
    depends_on:
      - mongo
    volumes:
      - db_mongo:/data/db
      # - ./data/configdb:/data/configdb
    command: npm start

  frontend:
    build: ./frontend
    ports:
      - '127.0.0.1:4200:4200'
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/usr/src/app/src
    command: npm start

  mongo:
    image: mongo
volumes:
  db_mongo:
